namePrefix: staging-
commonLabels:
  variant: staging
  org: acmeCorporation
commonAnnotations:
  note: Hello, I am staging!
resources:
- ../helloWorld
patchesStrategicMerge:
- map.yaml
- deploy.yaml
